In [178]:
# The City College of New York, City University of New York
# Written by Hasan Suca Kayman and Prof. M. Umit Uyar, September, 2025
# # Modified by Reaz Bhuiyan, March 2026
# NLP: Predicting financial stock movement based on tweets from Pres. Trump
# using ANNs

In [179]:
import re
import datetime
from datetime import date
import math
import numpy as np
import pandas as pd
from tensorflow import keras
from sklearn.preprocessing import MinMaxScaler
keras.utils.set_random_seed(42)

def print_weights(weights):
    # weights = model.get_weights();
    print('\n******* WEIGHTS OF ANN *******\n')
    for i in range(int(len(weights)/2)):
        print('Weights W%d:\n' %(i), weights[i*2])
        print('Bias b%d:\n' %(i), weights[(i*2)+1])

# Regular expression to remove punctuation and web links from tweets
# @\S+|https?://\S+ - matches either a substring which starts with @
# and contains non-whitespace characters \S+ OR a link(url) which
# starts with http(s)://
def clean_tweet(tweet):
    # delete all words starting with @
    temp = re.sub(r'@\w+','',tweet)
    # delete all words starting with #
    temp = re.sub(r'#\w+','',temp)
    # delete all words starting with url
    temp = re.sub(r'https?://\S+|www\.\S+','',temp)
    # delete all punctuation marks
    temp = re.sub(r'[^\w\s]','',temp)
    return temp

In [180]:
# read tweets
df = pd.read_csv('trumptwitter_2019_01_01_to_2020_03_11.csv')
df

                                                   text     created_at
0     The Media should view this as a time of unity ...  3/11/20 22:04
1     I will be addressing the Nation this evening a...  3/11/20 20:44
2     I am fully prepared to use the full power of t...  3/11/20 19:18
3     ....We have the greatest healthcare system exp...  3/11/20 19:17
4     I want to thank all of our Great Government of...  3/11/20 19:17
...                                                 ...            ...
7717  RT @GOPChairwoman: Jobless claims fell last we...   1/1/19 14:50
7718  The Democrats much as I suspected have allocat...   1/1/19 14:32
7719                                    Happy New Year!   1/1/19 14:25
7720  HAPPY NEW YEAR TO EVERYONE INCLUDING THE HATER...   1/1/19 13:08
7721  Dr. Sebastian Gorka a very good and talented g...   1/1/19 12:51

[7722 rows x 2 columns]

In [181]:
# clean-up the tweets:
df['clean_tweet'] = df['text'].apply(lambda X:clean_tweet(X.lower()))
df.iloc[7717,:]

text           RT @GOPChairwoman: Jobless claims fell last we...
created_at                                          1/1/19 14:50
clean_tweet    rt  jobless claims fell last week to a 49year ...
Name: 7717, dtype: object

In [182]:
# convert dates from string to date and eliminate hours:
df['created_at'] = pd.to_datetime(df['created_at']).dt.date
df.head()

/tmp/ipykernel_348/3970137872.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['created_at'] = pd.to_datetime(df['created_at']).dt.date

,text,created_at,clean_tweet
0,The Media should view this as a time of unity ...,2020-03-11,the media should view this as a time of unity ...
1,I will be addressing the Nation this evening a...,2020-03-11,i will be addressing the nation this evening a...
2,I am fully prepared to use the full power of t...,2020-03-11,i am fully prepared to use the full power of t...
3,....We have the greatest healthcare system exp...,2020-03-11,we have the greatest healthcare system experts...
4,I want to thank all of our Great Government of...,2020-03-11,i want to thank all of our great government of...

In [183]:
# define key words used in tweets that may be influential, which are
# selected by domain experts (e.g., in political science)
print('\n\n********** IDENTIFYING KEY WORDS **********\n\n')
key_words = ['Europe', 'China', 'tariff', 'Stock Market', 'economy', 'bank',
          'trade', 'jobs', 'money', 'dollar','currency','Xi','deal','growth']

# create a new column for number of keywords used in the tweet:
for key_word in key_words:
    df[key_word] = df.text.str.contains(key_word, case=False).astype(int)
df['noof_keywords'] = df[key_words].sum(axis=1)
# print noof_keyords column elements that are greater than 0 in the first 200 tweets:
for i in range(200):
    if (df.loc[i,'noof_keywords'] > 0):
        print (f"{i}: {df.loc[i,'noof_keywords']}")

********** IDENTIFYING KEY WORDS **********


2: 1
8: 1
29: 1
41: 1
60: 1
75: 1
89: 1
93: 1
105: 1
106: 1
112: 2
113: 1
151: 1
153: 2
154: 2
159: 1
173: 2
174: 1
175: 1
176: 1
181: 1
191: 1
196: 2

In [184]:
# combine tweet counts for the same day:
df_grouped = df.groupby('created_at')[key_words + ['noof_keywords']].sum()
df_grouped.reset_index(inplace=True)
df_grouped

,created_at,Europe,China,tariff,Stock Market,economy,bank,trade,jobs,money,dollar,currency,Xi,deal,growth,noof_keywords
0,2019-01-01,0,0,0,0,0,0,0,0,1,0,0,0,1,0,2
1,2019-01-02,0,0,0,0,0,0,1,1,0,1,0,1,1,0,5
2,2019-01-03,0,1,1,0,0,0,1,0,0,1,0,0,0,0,4
3,2019-01-04,0,1,0,0,0,0,0,1,0,0,0,0,0,1,3
4,2019-01-05,0,0,0,0,0,0,0,0,1,1,0,0,2,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,2020-03-07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
420,2020-03-08,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
421,2020-03-09,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
422,2020-03-10,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
423,2020-03-11,0,0,0,0,0,0,0,0,0,0,0,1,1,0,2

In [185]:
#% Stock prices
filename = "S&P500_2019_01_01_to_2020_03_11.csv"
snp_df = pd.read_csv(filename)
snp_df['date'] = pd.to_datetime(snp_df['Date']).dt.date
snp_df['percent change'] = snp_df['Close'].pct_change()
snp_df['percent change'] = snp_df['percent change'].shift(-1)
snp_df

/tmp/ipykernel_348/3266677461.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  snp_df['date'] = pd.to_datetime(snp_df['Date']).dt.date

,Date,Open,High,Low,Close,Adj Close,Volume,date,percent change
0,1/2/19,2476.959961,2519.489990,2467.469971,2510.030029,2510.030029,3733160000,2019-01-02,-0.024757
1,1/3/19,2491.919922,2493.139893,2443.959961,2447.889893,2447.889893,3822860000,2019-01-03,0.034336
2,1/4/19,2474.330078,2538.070068,2474.330078,2531.939941,2531.939941,4213410000,2019-01-04,0.007010
3,1/7/19,2535.610107,2566.159912,2524.560059,2549.689941,2549.689941,4104710000,2019-01-07,0.009695
4,1/8/19,2568.110107,2579.820068,2547.560059,2574.409912,2574.409912,4083030000,2019-01-08,0.004098
...,...,...,...,...,...,...,...,...,...
295,3/5/20,3075.699951,3083.040039,2999.830078,3023.939941,3023.939941,5575550000,2020-03-05,-0.017054
296,3/6/20,2954.199951,2985.929932,2901.540039,2972.370117,2972.370117,6552140000,2020-03-06,-0.075970
297,3/9/20,2863.889893,2863.889893,2734.429932,2746.560059,2746.560059,8423050000,2020-03-09,0.049396
298,3/10/20,2813.479980,2882.590088,2734.000000,2882.229980,2882.229980,7635960000,2020-03-10,-0.048868
299,3/11/20,2825.600098,2825.600098,2707.219971,2741.379883,2741.379883,7374110000,2020-03-11,NaN

In [186]:
# combine df and snp_df based on date:
df_combo = pd.merge(df_grouped, snp_df, left_on='created_at', right_on='date', how='inner')
df_combo

,created_at,Europe,China,tariff,Stock Market,economy,bank,trade,jobs,money,...,noof_keywords,Date,Open,High,Low,Close,Adj Close,Volume,date,percent change
0,2019-01-02,0,0,0,0,0,0,1,1,0,...,5,1/2/19,2476.959961,2519.489990,2467.469971,2510.030029,2510.030029,3733160000,2019-01-02,-0.024757
1,2019-01-03,0,1,1,0,0,0,1,0,0,...,4,1/3/19,2491.919922,2493.139893,2443.959961,2447.889893,2447.889893,3822860000,2019-01-03,0.034336
2,2019-01-04,0,1,0,0,0,0,0,1,0,...,3,1/4/19,2474.330078,2538.070068,2474.330078,2531.939941,2531.939941,4213410000,2019-01-04,0.007010
3,2019-01-07,0,0,0,0,0,0,0,1,0,...,3,1/7/19,2535.610107,2566.159912,2524.560059,2549.689941,2549.689941,4104710000,2019-01-07,0.009695
4,2019-01-08,0,1,1,0,0,0,1,1,0,...,4,1/8/19,2568.110107,2579.820068,2547.560059,2574.409912,2574.409912,4083030000,2019-01-08,0.004098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,2020-03-05,0,1,0,0,0,0,0,0,0,...,2,3/5/20,3075.699951,3083.040039,2999.830078,3023.939941,3023.939941,5575550000,2020-03-05,-0.017054
296,2020-03-06,0,0,0,0,0,0,0,1,0,...,1,3/6/20,2954.199951,2985.929932,2901.540039,2972.370117,2972.370117,6552140000,2020-03-06,-0.075970
297,2020-03-09,0,0,0,0,1,0,0,0,0,...,1,3/9/20,2863.889893,2863.889893,2734.429932,2746.560059,2746.560059,8423050000,2020-03-09,0.049396
298,2020-03-10,0,0,0,0,0,0,0,0,0,...,1,3/10/20,2813.479980,2882.590088,2734.000000,2882.229980,2882.229980,7635960000,2020-03-10,-0.048868
299,2020-03-11,0,0,0,0,0,0,0,0,0,...,2,3/11/20,2825.600098,2825.600098,2707.219971,2741.379883,2741.379883,7374110000,2020-03-11,NaN

In [187]:
features = [ 'Open', 'Volume','noof_keywords',] + key_words
features = features + ['percent change']
df = df_combo[features]
df

,Open,Volume,noof_keywords,Europe,China,tariff,Stock Market,economy,bank,trade,jobs,money,dollar,currency,Xi,deal,growth,percent change
0,2476.959961,3733160000,5,0,0,0,0,0,0,1,1,0,1,0,1,1,0,-0.024757
1,2491.919922,3822860000,4,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0.034336
2,2474.330078,4213410000,3,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0.007010
3,2535.610107,4104710000,3,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0.009695
4,2568.110107,4083030000,4,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0.004098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,3075.699951,5575550000,2,0,1,0,0,0,0,0,0,0,0,0,1,0,0,-0.017054
296,2954.199951,6552140000,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,-0.075970
297,2863.889893,8423050000,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.049396
298,2813.479980,7635960000,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-0.048868
299,2825.600098,7374110000,2,0,0,0,0,0,0,0,0,0,0,0,1,1,0,NaN

In [188]:
# Normalize the volume and open:
df = df.dropna()
open_min = df['Open'].min()
open_max = df['Open'].max()
vol_min = df['Volume'].min()
vol_max = df['Volume'].max()
keywds_min = df['noof_keywords'].min()
keywds_max = df['noof_keywords'].max()

df.loc[:,'Open'] = (df['Open'] - open_min)/(open_max - open_min)
df.loc[:,'Volume'] = (df['Volume'] - vol_min)/(vol_max - vol_min)
df.loc[:,'noof_keywords'] = (df['noof_keywords'] - keywds_min)/(keywds_max - keywds_min)
df

/tmp/ipykernel_348/1245740493.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.335285   0.34762794 0.40136859 0.3864112  0.38342798 0.37922422
 0.33134131 0.29418726 0.32583033 0.31315439 0.35325726 0.34066663
 0.37017686 0.35934754 0.28058112 0.29401663 0.34641979 0.31872453
 0.30377953 0.35381317 0.49827378 0.3388778  0.28391523 0.31151692
 0.29944367 0.38569292 0.32003451 0.28420832 0.34830357 0.32669998
 0.34953236 0.32265446 0.30784018 0.34936035 0.31141784 0.29326807
 0.34508505 0.32324753 0.33995935 0.4266214  0.3681885  0.3609685
 0.31499276 0.34263847 0.35891134 0.29262409 0.33746875 0.29139943
 0.3398245  0.29903637 0.64207939 0.31038307 0.31974417 0.34051939
 0.30964139 0.40464216 0.2862187  0.27100949 0.28571645 0.25616494
 0.33632252 0.30330618 0.26837441 0.31011475 0.23648915 0.25460315
 0.24183501 0.23549842 0.24298399 0.2259433  0.32913829 0.24655478
 0.28974545 0.31727833 0.30414417 0.23411826 0.32178206 0.29617837
 0.29291994 0.26859457 0.25074477 0.36090245 0.32327092 0.34157756
 0.28092651 0.25937795 0.33995522 0.30124627 0.32230358 0.30727463
 0.35742111 0.27880743 0.25173138 0.28091825 0.26989491 0.27414958
 0.26449401 0.26089021 0.35713902 0.21890493 0.38870916 0.33072898
 0.27207454 0.36939115 0.36427096 0.34591754 0.30992073 0.28894735
 0.2647073  0.26318817 0.30986431 0.23909672 0.24400638 0.22371276
 0.20827514 0.29461795 0.27401473 0.35905995 0.50962185 0.25314869
 0.31394147 0.30019223 0.25131445 0.56749471 0.30502758 0.26286205
 0.09180563 0.15654623 0.22126619 0.23828212 0.25562416 0.25567645
 0.23095478 0.21719591 0.27439451 0.25938896 0.2752105  0.27022653
 0.23491223 0.27756075 0.29342907 0.32319111 0.26984538 0.26243135
 0.32168574 0.45778837 0.47689723 0.35475575 0.44269338 0.39322665
 0.43966887 0.38663962 0.28264929 0.21398427 0.35185784 0.41500775
 0.37723174 0.30294703 0.26369317 0.24352339 0.23594012 0.21938516
 0.36337517 0.21480575 0.30782917 0.24780558 0.25864453 0.23556309
 0.29312772 0.25686533 0.35696289 0.2630602  0.37240052 0.42577377
 0.36203354 0.34336226 0.3059619  0.409794   0.32684721 0.29433174
 0.26897848 0.6602443  0.2600756  0.35386133 0.27827766 0.24502877
 0.2679272  0.2684721  0.31118805 0.35996538 0.30370247 0.23313853
 0.22616346 0.28344876 0.1968101  0.26429449 0.31427309 0.17344519
 0.28128702 0.26502654 0.25035673 0.27076731 0.27177594 0.30648892
 0.28846024 0.32970384 0.28536419 0.3061229  0.31557619 0.34118401
 0.39116812 0.36239819 0.39220977 0.43889555 0.43505093 0.39190567
 0.30308464 0.23928937 0.29852449 0.30447855 0.27238827 0.28058663
 0.29448998 0.31559545 0.3768038  0.3335512  0.26560584 0.30478815
 0.45395752 0.23895362 0.06143676 0.27137964 0.32430844 0.33003821
 0.28335244 0.30037799 0.28200944 0.28170671 0.26915048 0.37072177
 0.3357955  0.37912928 0.34964794 0.37394029 0.33353607 0.70971653
 0.24274044 0.         0.11890782 0.15578391 0.23622909 0.21978834
 0.29745669 0.297875   0.32715406 0.29224569 0.33359661 0.32224441
 0.26370555 0.29719938 0.3259239  0.33303932 0.30802869 0.33047028
 0.38649789 0.31969326 0.33964699 0.3317032  0.34766096 0.30687834
 0.31482901 0.34272791 0.44463357 0.33869066 0.37135887 0.38820279
 0.35389023 0.33493961 0.29636963 0.33905393 0.36187255 0.30295942
 0.28917165 0.33715089 0.31698249 0.3730101  0.35814215 0.48799625
 0.5909986  0.57539447 0.79290687 1.         0.69900142 0.69618607
 0.51448748 0.58880246 0.72318368 0.98062557 0.87232002]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,'Volume'] = (df['Volume'] - vol_min)/(vol_max - vol_min)
/tmp/ipykernel_348/1245740493.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.0877193  0.07017544 0.05263158 0.05263158 0.07017544 0.14035088
 0.         0.07017544 0.0877193  0.03508772 0.01754386 0.
 0.05263158 0.         0.         0.03508772 0.03508772 0.07017544
 0.         0.05263158 0.29824561 0.0877193  0.         0.01754386
 0.         0.         0.         0.         0.05263158 0.03508772
 0.05263158 0.         0.07017544 0.05263158 0.         0.
 0.10526316 0.03508772 0.05263158 0.         0.0877193  0.01754386
 0.03508772 0.01754386 0.         0.0877193  0.01754386 0.03508772
 0.05263158 0.0877193  0.03508772 0.10526316 0.03508772 0.
 0.         0.07017544 0.         0.         0.01754386 0.05263158
 0.0877193  0.03508772 0.15789474 0.01754386 0.05263158 0.19298246
 0.03508772 0.14035088 0.01754386 0.03508772 0.01754386 0.
 0.03508772 0.01754386 0.         0.0877193  0.07017544 0.0877193
 0.05263158 0.0877193  0.03508772 0.07017544 0.03508772 0.0877193
 0.12280702 0.1754386  0.         0.28070175 0.         1.
 0.40350877 0.42105263 0.         0.         0.         0.28070175
 0.03508772 0.12280702 0.01754386 0.10526316 0.         0.
 0.12280702 0.12280702 0.12280702 0.         0.21052632 0.01754386
 0.10526316 0.21052632 0.31578947 0.03508772 0.14035088 0.
 0.03508772 0.12280702 0.03508772 0.0877193  0.05263158 0.05263158
 0.07017544 0.07017544 0.03508772 0.0877193  0.03508772 0.10526316
 0.15789474 0.03508772 0.03508772 0.15789474 0.10526316 0.15789474
 0.40350877 0.15789474 0.01754386 0.07017544 0.03508772 0.01754386
 0.07017544 0.19298246 0.01754386 0.07017544 0.12280702 0.05263158
 0.1754386  0.03508772 0.28070175 0.03508772 0.21052632 0.0877193
 0.10526316 0.05263158 0.01754386 0.01754386 0.12280702 0.33333333
 0.24561404 0.05263158 0.12280702 0.07017544 0.22807018 0.03508772
 0.49122807 0.03508772 0.07017544 0.05263158 0.03508772 0.1754386
 0.22807018 0.28070175 0.01754386 0.15789474 0.10526316 0.
 0.12280702 0.26315789 0.07017544 0.22807018 0.10526316 0.10526316
 0.         0.07017544 0.01754386 0.05263158 0.07017544 0.14035088
 0.05263158 0.24561404 0.21052632 0.03508772 0.0877193  0.
 0.14035088 0.15789474 0.14035088 0.0877193  0.15789474 0.10526316
 0.03508772 0.05263158 0.10526316 0.05263158 0.01754386 0.12280702
 0.10526316 0.03508772 0.05263158 0.01754386 0.07017544 0.07017544
 0.14035088 0.1754386  0.10526316 0.21052632 0.0877193  0.07017544
 0.         0.0877193  0.0877193  0.05263158 0.0877193  0.07017544
 0.10526316 0.03508772 0.07017544 0.0877193  0.         0.01754386
 0.03508772 0.01754386 0.         0.1754386  0.         0.03508772
 0.01754386 0.15789474 0.03508772 0.07017544 0.         0.07017544
 0.26315789 0.21052632 0.14035088 0.03508772 0.07017544 0.15789474
 0.         0.07017544 0.03508772 0.0877193  0.         0.0877193
 0.         0.05263158 0.         0.01754386 0.         0.05263158
 0.03508772 0.0877193  0.03508772 0.07017544 0.24561404 0.0877193
 0.03508772 0.10526316 0.07017544 0.07017544 0.03508772 0.01754386
 0.10526316 0.07017544 0.01754386 0.07017544 0.05263158 0.
 0.         0.10526316 0.03508772 0.0877193  0.05263158 0.03508772
 0.         0.28070175 0.05263158 0.         0.10526316 0.01754386
 0.01754386 0.         0.         0.0877193  0.10526316 0.10526316
 0.0877193  0.03508772 0.01754386 0.01754386 0.01754386]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,'noof_keywords'] = (df['noof_keywords'] - keywds_min)/(keywds_max - keywds_min)

,Open,Volume,noof_keywords,Europe,China,tariff,Stock Market,economy,bank,trade,jobs,money,dollar,currency,Xi,deal,growth,percent change
0,0.002902,0.335285,0.087719,0,0,0,0,0,0,1,1,0,1,0,1,1,0,-0.024757
1,0.019412,0.347628,0.070175,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0.034336
2,0.000000,0.401369,0.052632,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0.007010
3,0.067629,0.386411,0.052632,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0.009695
4,0.103496,0.383428,0.070175,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0.004098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,0.630623,0.514487,0.087719,0,0,0,0,2,0,0,0,1,1,0,0,1,0,-0.033922
295,0.663676,0.588802,0.035088,0,1,0,0,0,0,0,0,0,0,0,1,0,0,-0.017054
296,0.529588,0.723184,0.017544,0,0,0,0,0,0,0,1,0,0,0,0,0,0,-0.075970
297,0.429921,0.980626,0.017544,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.049396
298,0.374288,0.872320,0.017544,0,0,0,0,0,0,0,0,0,0,1,0,0,0,-0.048868

In [189]:
# Prepare input and output features for ANN
X = np.array(df.iloc[:,:-1])
Y = np.array(df.loc[:,'percent change'])
X.shape, Y.shape

((299, 17), (299,))

In [190]:
X

array([[0.00290236, 0.335285  , 0.0877193 , ..., 1.        , 1.        ,
        0.        ],
       [0.01941227, 0.34762794, 0.07017544, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.40136859, 0.05263158, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.52958763, 0.72318368, 0.01754386, ..., 0.        , 0.        ,
        0.        ],
       [0.42992084, 0.98062557, 0.01754386, ..., 0.        , 0.        ,
        0.        ],
       [0.37428812, 0.87232002, 0.01754386, ..., 0.        , 0.        ,
        0.        ]])

In [191]:
Y

array([-2.47567301e-02,  3.43357143e-02,  7.01043485e-03,  9.69528514e-03,
        4.09804552e-03,  4.51841892e-03, -1.46297914e-04, -5.25752542e-03,
        1.07216889e-02,  2.22198555e-03,  7.59140027e-03,  1.31830530e-02,
       -1.41573063e-02,  2.20291284e-03,  1.37572557e-03,  8.48869420e-03,
       -7.84682745e-03, -1.45624671e-03,  1.55492610e-02,  8.59739601e-03,
        8.98609856e-04,  6.77623666e-03,  4.70842038e-03, -2.22443807e-03,
       -9.35713993e-03,  6.76201093e-04,  7.09103093e-04,  1.28902245e-02,
        3.02399473e-03, -2.65164162e-03,  1.08787529e-02,  1.49874328e-03,
        1.77711061e-03, -3.52643666e-03,  6.41110237e-03,  1.23186237e-03,
       -7.90457069e-04, -5.44049198e-04, -2.82550847e-03,  6.89532053e-03,
       -3.88055820e-03, -1.13153309e-03, -6.52409859e-03, -8.12571737e-03,
       -2.13168911e-03,  1.46660421e-02,  2.95331831e-03,  6.94958369e-03,
       -8.68022593e-04,  4.98490290e-03,  3.70594692e-03, -1.30561539e-04,
       -2.94435364e-03,  1.08524813e-02, -1.89745013e-02, -8.39020831e-04,
        7.18272604e-03, -4.64432498e-03,  3.58948145e-03,  6.73428004e-03,
        1.15686001e-02,  1.74557672e-05,  2.14837684e-03,  2.08463535e-03,
        4.63643254e-03,  1.04746020e-03, -6.06749461e-03,  3.47787165e-03,
        3.81229209e-05,  6.60932430e-03, -6.29369114e-04,  5.09358187e-04,
       -2.27381198e-03,  1.57909224e-03,  1.01201777e-03,  8.84120581e-03,
       -2.19176330e-03, -3.68973610e-04,  4.68529216e-03,  1.07152201e-03,
        9.51417068e-04, -7.50216320e-03, -2.12398547e-03,  9.63827936e-03,
       -4.47098847e-03, -1.65116514e-02, -1.60542533e-03, -3.02142488e-03,
        3.72029704e-03, -2.41305571e-02,  8.01594457e-03,  5.83897514e-03,
        8.89528697e-03, -5.83733333e-03, -6.74937798e-03,  8.49583561e-03,
       -2.82439592e-03, -1.19141502e-02,  1.35355923e-03, -8.37567692e-03,
       -6.91191224e-03,  2.09847107e-03, -1.31953725e-02, -2.76524052e-03,
        2.14323708e-02,  8.16185449e-03,  6.13558679e-03,  1.04976976e-02,
        4.66004427e-03, -3.49879970e-04, -2.03757920e-03,  4.09738202e-03,
       -1.61151221e-03,  9.31749447e-04,  9.71739983e-03,  2.98516357e-03,
        9.47218529e-03, -1.25922289e-03, -1.73188692e-03, -9.49639740e-03,
       -1.23393392e-03,  3.82317570e-03,  5.75745267e-03,  7.67230091e-03,
        2.92812601e-03,  7.67237847e-03, -1.80590152e-03, -4.83544445e-03,
        1.23655709e-03,  4.51068942e-03,  2.28522682e-03,  4.62017474e-03,
        1.75869093e-04, -3.40377860e-03, -6.53124351e-03,  3.58199760e-03,
       -6.17673452e-03,  2.82869496e-03,  6.84748287e-03,  4.68814799e-03,
       -5.26240137e-03,  7.38769092e-03, -1.61611437e-03, -2.57865489e-03,
       -1.08855262e-02, -8.99879380e-03, -7.28274001e-03, -2.97778201e-02,
        1.30170174e-02,  7.66875908e-04,  1.87623036e-02, -6.61660651e-03,
       -1.23173221e-02,  1.51316883e-02, -2.92927527e-02,  2.46426803e-03,
        1.44261247e-02,  1.21058652e-02, -7.91472740e-03,  8.24679864e-03,
       -5.06075042e-04, -2.59463368e-02,  1.09829880e-02, -3.20318074e-03,
        6.54548006e-03,  1.26872919e-02,  6.42787323e-04, -6.89910037e-03,
        1.08420789e-02,  1.30098137e-02,  9.10605175e-04, -9.40101600e-05,
        3.22304376e-04,  7.22968117e-03,  2.87915286e-03, -7.24414103e-04,
       -3.13558678e-03,  2.58175229e-03,  3.42691891e-04,  1.99748565e-05,
       -4.89557661e-03, -9.69358984e-05, -8.41637111e-03,  6.15857156e-03,
       -2.42891641e-03, -5.31635245e-03,  5.04760662e-03, -1.22583733e-02,
       -1.79032031e-02,  7.97191281e-03,  1.42168976e-02, -4.47829477e-03,
       -1.55608190e-02,  9.10449229e-03,  6.41569556e-03,  1.09389776e-02,
       -1.38711901e-03,  9.95567688e-03, -1.99954305e-03,  2.76283165e-03,
       -3.91934495e-03,  6.87161621e-03, -3.56866655e-03,  2.84714903e-03,
        1.92044618e-03,  4.07270058e-03,  5.58133785e-03, -8.32405217e-04,
        3.25337017e-03, -3.02286058e-03,  9.66231200e-03,  3.70408924e-03,
       -1.18569943e-03,  7.02497192e-04,  2.73009540e-03,  2.56067593e-03,
       -1.96246714e-03,  1.56464604e-03,  7.11534535e-04,  8.37042820e-04,
        7.69548797e-03,  5.03152747e-04, -5.92594236e-04, -3.75618434e-03,
       -1.58275225e-03,  2.17493569e-03,  7.50729151e-03,  2.19557040e-03,
        4.17442427e-03, -4.01121992e-03, -8.63102063e-03, -6.63809511e-03,
        6.32356760e-03,  1.50025122e-03,  9.13572418e-03, -3.16282134e-03,
       -1.09693397e-03,  2.90815795e-03,  8.57522560e-03,  7.25819518e-05,
        7.14778517e-03,  3.35292427e-04, -4.32300186e-04,  4.45929181e-03,
        4.94478123e-03,  8.66143581e-04, -1.95448215e-04,  5.12816658e-03,
        3.39848956e-05, -5.78082261e-03,  2.94602159e-03,  8.37880288e-03,
       -7.05987056e-03,  3.53337269e-03, -2.80323845e-03,  4.90245131e-03,
        6.65526250e-03, -2.85517853e-03,  6.97621520e-03, -1.51453293e-03,
        1.87019697e-03,  8.36655317e-03,  3.86216207e-03, -2.65197761e-03,
        2.89076090e-04,  1.14097659e-03, -9.04216087e-03, -1.57307117e-02,
        1.00535845e-02, -8.66874224e-04,  3.13435886e-03, -1.77058202e-02,
        7.25461378e-03,  1.49804142e-02,  1.12505957e-02,  3.32567291e-03,
       -5.40085357e-03,  7.32639782e-03,  1.68847252e-03,  6.46264642e-03,
       -1.63044581e-03,  1.84353341e-03, -2.91994262e-03,  4.70578580e-03,
       -3.81551980e-03, -1.05181029e-02, -3.35136265e-02, -3.02799957e-02,
       -3.77854049e-03, -4.41632426e-02, -8.23834042e-03,  4.60392287e-02,
       -2.81078960e-02,  4.22025908e-02, -3.39220771e-02, -1.70538519e-02,
       -7.59696973e-02,  4.93963060e-02, -4.88684449e-02])

In [192]:
# create a model for the ANN:
model = keras.Sequential()
alpha = 0.01
# add a hidden layer that takes in 17 input features
model.add(keras.layers.Input(shape=(17,)))
# add a hidden layer with 4 neurons

model.add(keras.layers.Dense(10, activation='sigmoid'))
model.add(keras.layers.Dense(4, activation='sigmoid',))
# add another hidden layer with 8 neurons
model.add(keras.layers.Dense(8, activation='sigmoid'))
# add an output layer with one output (the slope of the cognitive decline)
# activation function default to linear
model.add(keras.layers.Dense(16, activation='sigmoid'))
model.add(keras.layers.Dense(8, activation='sigmoid'))

model.add(keras.layers.Dense(1, activation='tanh'))

# set optimizer to Adam which is a gradient descent method that updates
# the weights to minimize the loss
# set loss to mean_absolute_error which does the average absolute
# difference between actual output and estimated output
# set learning rate to 0.01, learning rate is the rate at which model
# paremeters are updated)
# metrics is utilized to see how the model is performing each epoch
model.compile(optimizer=keras.optimizers.SGD(learning_rate=alpha),
              loss='mean_absolute_error',
              metrics=[keras.metrics.RootMeanSquaredError()]
              )
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_49 (Dense)                │ (None, 10)             │           180 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_50 (Dense)                │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_51 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_52 (Dense)                │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_53 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_54 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 553 (2.16 KB)

 Trainable params: 553 (2.16 KB)

 Non-trainable params: 0 (0.00 B)

In [193]:
# print the randomly initialized weights:
weights = model.get_weights()
print_weights(weights)

******* WEIGHTS OF ANN *******

Weights W0:
 [[ 0.3377039   0.15332767 -0.13320878  0.4242542  -0.3978078   0.14362028
   0.44359156 -0.31309545  0.02242875  0.12328133]
 [-0.38992858 -0.05057463  0.4393808  -0.02796268  0.00277787  0.25047234
  -0.4536515  -0.29002607  0.01342708 -0.4087787 ]
 [-0.4359125   0.32806602  0.39166918 -0.22387867  0.33896992 -0.35122037
  -0.03555766  0.05913475  0.06287768 -0.28268993]
 [-0.27370435  0.4611881  -0.36779645 -0.05316189 -0.22147663 -0.35730457
   0.21980932 -0.29949212  0.17092726  0.1418164 ]
 [-0.43121183  0.05999646 -0.15639156 -0.10668188  0.4285269  -0.08448127
   0.02967039 -0.23068678 -0.35561138  0.20348647]
 [ 0.1097559   0.00750056 -0.4452303  -0.35857022  0.27472708  0.3452371
  -0.06425259 -0.17558962 -0.44023675 -0.4349247 ]
 [ 0.24424765  0.30982307 -0.11692593  0.20700082 -0.1733909   0.26296756
  -0.17415372 -0.07216227  0.33449063  0.30866495]
 [ 0.17585364  0.37419376  0.33262125 -0.25871468  0.12772372 -0.38669014
   0.42814824  0.20638797  0.05711731 -0.2943753 ]
 [-0.28459284  0.4456146  -0.42361864 -0.17397422 -0.24774468 -0.32350326
   0.34266344  0.31856295  0.11841902  0.03406557]
 [ 0.04266509  0.20207718 -0.01734808 -0.34792516  0.37682858 -0.12331101
   0.2857311   0.3367838  -0.11201161 -0.4139939 ]
 [ 0.4275265   0.31034836  0.05870774 -0.29188266 -0.28167042  0.2335873
  -0.4271265  -0.12768438  0.36717257 -0.04058763]
 [-0.2923203   0.16188458 -0.02794898  0.3578941  -0.02829021 -0.17013761
   0.40186468 -0.37411612 -0.31964666 -0.18588716]
 [ 0.01603121 -0.39461893 -0.4194478   0.407351    0.36199185 -0.19748059
   0.3415629  -0.35121238  0.1155124  -0.3047878 ]
 [ 0.2627776  -0.21288732  0.10909584  0.08487669 -0.1978671  -0.40016523
   0.01338843  0.10519752  0.40431133 -0.26278615]
 [-0.38693124 -0.2835514   0.03986058  0.3538989   0.28370753  0.08989868
   0.02473414  0.4687179  -0.16886455 -0.12590858]
 [ 0.08835241  0.4455069  -0.36821556 -0.0976474  -0.23348017 -0.43267405
   0.29483137 -0.2500314   0.3147433   0.3213534 ]
 [ 0.0696142   0.07178673 -0.39365438  0.35446277  0.45497492 -0.4319789
   0.3322735  -0.0583317   0.28390262 -0.2869544 ]]
Bias b0:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Weights W1:
 [[ 0.6273624  -0.02354413  0.34840393  0.317995  ]
 [ 0.41374016 -0.49926662  0.2659799   0.03849208]
 [-0.56064653 -0.24921253 -0.3616275   0.02280134]
 [ 0.1497528   0.18311709 -0.00293338 -0.6044589 ]
 [ 0.3082983   0.441141   -0.5064818   0.08345389]
 [ 0.3672104   0.6088959   0.06919688  0.58557856]
 [ 0.22407556  0.47281444 -0.04529303 -0.3785848 ]
 [ 0.16334015  0.04401875 -0.3310734   0.06147319]
 [ 0.53560245  0.38870215 -0.4575632  -0.5777072 ]
 [-0.52718186 -0.43753916 -0.51614237 -0.19898641]]
Bias b1:
 [0. 0. 0. 0.]
Weights W2:
 [[ 0.48486143 -0.03265721 -0.1664927  -0.44360653 -0.1493625   0.5084316
  -0.570976   -0.08805269]
 [-0.60829717 -0.54956806 -0.22818321  0.1983586  -0.23701534  0.69641584
   0.10778266 -0.29294217]
 [-0.05337358  0.08854949 -0.18101984 -0.03302103 -0.08845967  0.64129645
  -0.49449766 -0.37928554]
 [-0.53250134  0.44042248  0.34351498  0.09364355  0.511494   -0.42243296
   0.39585572  0.35803252]]
Bias b2:
 [0. 0. 0. 0. 0. 0. 0. 0.]
Weights W3:
 [[ 0.31594765  0.13643801  0.0011673   0.18323648  0.35946143  0.19001913
   0.36795533  0.39437997 -0.30707276  0.17959666 -0.26107168  0.23881447
  -0.11033118 -0.14220226 -0.02307498 -0.4132663 ]
 [-0.2540958  -0.02064347  0.3960384  -0.1394602   0.05549872 -0.0817405
   0.44939005  0.3323344  -0.41415155 -0.0677042   0.44280684 -0.45985234
   0.4811616   0.03662109  0.30028224 -0.03720343]
 [-0.3544321  -0.34293354  0.38968647  0.43474543 -0.33006954 -0.0810436
   0.43466127  0.0696007   0.10660672 -0.22601354  0.17967808  0.24449241
   0.06483471  0.3989154  -0.4379853  -0.45823693]
 [ 0.24743044 -0.24644732 -0.21583295 -0.3614726   0.49201322 -0.06876016
   0.06016755  0.08354521  0.08028555  0.33351433  0.4853356   0.24898994
   0.43628037  0.2785474   0.13806212 -0.3358351 ]
 [-0.11542344  0.13906157 -0.14147437  0.37083745 -0.16277874  0.05301261
  -0.39502895  0.14353538 -0.4898528   0.3705368  -0.4542849   0.43103635
   0.15948641  0.10473192 -0.442477    0.3515892 ]
 [ 0.20786214 -0.14764953 -0.32055748  0.43064165 -0.4708836   0.3158058
  -0.1395421  -0.0552839  -0.42673123 -0.01179588 -0.10379338  0.42165053
  -0.00141561 -0.12717223  0.07370365  0.46451712]
 [-0.01515055  0.13463676 -0.29092038  0.30433583 -0.17958057 -0.06461155
   0.08897686 -0.4759668  -0.25422907 -0.30261588  0.3110429   0.07163584
   0.37442565  0.41768444 -0.16943395 -0.4812832 ]
 [-0.4529575  -0.20916927 -0.2742864   0.44535446 -0.37462008  0.24607873
   0.4729873   0.39860582  0.27534747 -0.30730462 -0.06809807 -0.13029265
   0.1692599  -0.1720308  -0.18465984 -0.43321252]]
Bias b3:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Weights W4:
 [[ 0.49564183 -0.30673134  0.32530367 -0.45215595  0.19169259 -0.43079627
  -0.23724604 -0.4891926 ]
 [ 0.30289483 -0.44093764  0.20079052  0.21811938 -0.17331088  0.20092571
  -0.10594773 -0.14515972]
 [ 0.15399408 -0.38577676 -0.09772384  0.2929325  -0.10179389  0.15709388
   0.02541828 -0.39159667]
 [-0.2293297  -0.05696416 -0.05418503  0.0106647   0.02616227  0.4962616
  -0.03467    -0.09718192]
 [ 0.00772595  0.05285549  0.43314397 -0.05065644  0.18485558  0.16235447
  -0.4059142   0.38527715]
 [-0.35266554 -0.03314698 -0.2637235   0.343724   -0.38507652  0.4528246
   0.00167906 -0.4066739 ]
 [-0.19251907  0.2824638  -0.10009074  0.48380816  0.10409379  0.18876171
  -0.4625424  -0.1874845 ]
 [-0.11701345 -0.33925378 -0.3502456   0.11550641 -0.2160219   0.11023915
  -0.37885535 -0.16546297]
 [ 0.26903486  0.23805666 -0.23868191  0.0864495   0.4427035  -0.02186382
  -0.25623977 -0.42005312]
 [ 0.14215243  0.18200195 -0.06791806  0.14384103 -0.3515836  -0.46658087
  -0.31186724 -0.48393047]
 [-0.02841723  0.28037608 -0.41885746 -0.4964913   0.09007168  0.06293726
   0.04318607  0.36649132]
 [-0.29323792  0.41818035  0.34709823 -0.42297626 -0.21165526  0.20801055
  -0.35845292  0.00601482]
 [ 0.16846824 -0.08969069 -0.338521   -0.2927413   0.08058548 -0.12044275
  -0.23301578  0.2464925 ]
 [-0.19324338 -0.29623914  0.21137595 -0.16266418 -0.32465017 -0.17754996
   0.10270298  0.27022743]
 [-0.24912763 -0.48351705 -0.27913237  0.17487228  0.05702138  0.1405927
  -0.21573317 -0.09743214]
 [ 0.1506095  -0.19973087 -0.16760528  0.24610102 -0.40390146 -0.41426742
  -0.21893966  0.1501106 ]]
Bias b4:
 [0. 0. 0. 0. 0. 0. 0. 0.]
Weights W5:
 [[ 0.5676311 ]
 [-0.39512205]
 [-0.12130654]
 [ 0.16512752]
 [ 0.7579261 ]
 [-0.2557655 ]
 [ 0.783237  ]
 [ 0.74901843]]
Bias b5:
 [0.]

In [194]:
## train the ANN model using 120 iterations
model.fit(X, Y, epochs=200, verbose = 0)
print('\n\n********** ANN training complete **********\n\n')

********** ANN training complete **********

In [195]:
# print the weights of the trained ANN:
weights = model.get_weights()
print_weights(weights)

******* WEIGHTS OF ANN *******

Weights W0:
 [[ 0.33779272  0.15348779 -0.1332844   0.4243033  -0.39783046  0.14357197
   0.44361386 -0.3130934   0.02250453  0.12324684]
 [-0.38986462 -0.05046521  0.43932617 -0.02792721  0.00276226  0.25043815
  -0.45364332 -0.29002452  0.01348129 -0.40880078]
 [-0.4359202   0.3280938   0.39166984 -0.22387867  0.33897164 -0.35121676
  -0.03555498  0.05913286  0.06286589 -0.28269085]
 [-0.2737073   0.46116427 -0.3677833  -0.05315543 -0.22148176 -0.35729113
   0.21981107 -0.29949874  0.17093915  0.14181423]
 [-0.43132883  0.06042657 -0.15630509 -0.10668392  0.4285446  -0.08444518
   0.02967168 -0.23070617 -0.35580325  0.2035127 ]
 [ 0.10963058  0.00763797 -0.4452024  -0.3586496   0.2747662   0.3452885
  -0.06424001 -0.17561074 -0.44040105 -0.43493277]
 [ 0.24427608  0.30986783 -0.11694869  0.20699477 -0.17339869  0.26296622
  -0.1741471  -0.07215911  0.3345045   0.30865708]
 [ 0.17578445  0.3743889   0.3326506  -0.25870672  0.12777655 -0.38661984
   0.42816252  0.20638101  0.05704303 -0.29439345]
 [-0.28467128  0.44552544 -0.42357713 -0.17404544 -0.24771243 -0.32343933
   0.34266365  0.3185488   0.11832159  0.03407249]
 [ 0.04281313  0.20249227 -0.01748813 -0.34777814  0.37675413 -0.12346788
   0.28572428  0.33681658 -0.11187207 -0.41399562]
 [ 0.42750022  0.3103258   0.05876326 -0.29193154 -0.28162763  0.23370923
  -0.42710868 -0.12770012  0.36714795 -0.04062175]
 [-0.29218835  0.1620407  -0.02800679  0.35795483 -0.02832247 -0.17020842
   0.4018605  -0.37411523 -0.31957528 -0.18589024]
 [ 0.01603556 -0.39416045 -0.41946992  0.40747908  0.3619893  -0.197511
   0.34156433 -0.35118872  0.11549416 -0.30478275]
 [ 0.26273233 -0.21298304  0.10910911  0.08483664 -0.19786175 -0.40013093
   0.01339     0.10518976  0.40426025 -0.26278657]
 [-0.3869767  -0.2835097   0.03985183  0.353912    0.28374866  0.08997992
   0.02476554  0.46869093 -0.16899352 -0.12593378]
 [ 0.08827689  0.44542396 -0.36818025 -0.09776091 -0.23345813 -0.43259352
   0.29484624 -0.2500744   0.31461582  0.32133868]
 [ 0.06955848  0.07169091 -0.39364192  0.35443217  0.4549972  -0.4319118
   0.33227834 -0.05833941  0.2838498  -0.2869634 ]]
Bias b0:
 [ 1.12059824e-04  1.84754797e-04 -1.09146124e-04  5.57774183e-05
 -2.37409076e-05 -3.43991996e-05  3.43694119e-05 -3.35704658e-06
  8.92008829e-05 -5.52530473e-05]
Weights W1:
 [[ 0.6276503  -0.0236144   0.3485051   0.31784356]
 [ 0.41383964 -0.49910283  0.26610526  0.03843666]
 [-0.5601564  -0.24951427 -0.36152688  0.02252035]
 [ 0.15023115  0.1828764  -0.00280653 -0.60473394]
 [ 0.308487    0.44116572 -0.5063688   0.08332512]
 [ 0.3676589   0.60865     0.06929775  0.58533037]
 [ 0.2243682   0.4727761  -0.04515571 -0.37876874]
 [ 0.16356173  0.04397749 -0.33098418  0.06133453]
 [ 0.53579366  0.38873482 -0.45745736 -0.57780683]
 [-0.5270688  -0.4375088  -0.51605695 -0.19906251]]
Bias b1:
 [ 0.00056203 -0.00013481  0.00021713 -0.00032722]
Weights W2:
 [[ 0.48629022 -0.03330213 -0.16603813 -0.44353393 -0.14800812  0.5096563
  -0.57192856 -0.08750357]
 [-0.606554   -0.55028707 -0.22750562  0.19847237 -0.23554459  0.6977377
   0.10681052 -0.29217297]
 [-0.05256157  0.08820327 -0.1807248  -0.03297237 -0.0877443   0.64193773
  -0.4949825  -0.37894374]
 [-0.5313784   0.43996233  0.34395823  0.09371828  0.51243246 -0.42159215
   0.39523765  0.35853428]]
Bias b2:
 [ 0.00235809 -0.00101245  0.00084309  0.00013847  0.0020955   0.00188263
 -0.00142703  0.0009808 ]
Weights W3:
 [[ 0.31593445  0.13600552  0.00155881  0.18421648  0.35824636  0.19411546
   0.3696606   0.3965952  -0.30741867  0.18312939 -0.26207787  0.24265264
  -0.11156289 -0.14196745 -0.02245779 -0.41315752]
 [-0.2541843  -0.02108745  0.39648902 -0.13827603  0.05424521 -0.07707439
   0.45142812  0.3347927  -0.4144967  -0.06376093  0.44169313 -0.455449
   0.47975528  0.03685586  0.30093616 -0.03713603]
 [-0.35453358 -0.3433708   0.3901392   0.43594518 -0.33130595 -0.07636147
   0.43672144  0.07205621  0.10626841 -0.2220701   0.17856535  0.24891677
   0.06342289  0.39914587 -0.43733662 -0.45817855]
 [ 0.24730064 -0.24688552 -0.21536107 -0.36020306  0.49077255 -0.06389392
   0.06234146  0.08607512  0.07995029  0.33758575  0.48419014  0.2535999
   0.43481204  0.27877587  0.13872008 -0.33579323]
 [-0.11553461  0.13859934 -0.14099313  0.3721152  -0.16408546  0.05798658
  -0.3928342   0.14614062 -0.49020937  0.37472218 -0.45546493  0.43573812
   0.15798666  0.10497489 -0.44179088  0.3516479 ]
 [ 0.20772213 -0.14832953 -0.31986365  0.43246517 -0.47280395  0.32298037
  -0.13640457 -0.05150882 -0.42725912 -0.00573738 -0.10550416  0.4284241
  -0.00357778 -0.12681285  0.07470693  0.46461812]
 [-0.01528282  0.13424452 -0.2904867   0.30551067 -0.18069233 -0.0601575
   0.09098431 -0.47366354 -0.25452697 -0.29890376  0.31000066  0.07586078
   0.3730806   0.4178873  -0.16884103 -0.48125628]
 [-0.4530488  -0.20959692 -0.27384752  0.44650957 -0.37582812  0.25061047
   0.47497302  0.4009882   0.2750157  -0.3034803  -0.06917761 -0.12601268
   0.16789393 -0.1718048  -0.18402778 -0.43315086]]
Bias b3:
 [-0.00020812 -0.00096747  0.00099111  0.00261556 -0.00273291  0.01025904
  0.00449743  0.00539199 -0.00075023  0.00865554 -0.0024434   0.00968872
 -0.00309279  0.00051055  0.00142985  0.00013824]
Weights W4:
 [[ 4.78845000e-01 -2.99792230e-01  3.26064706e-01 -4.59128469e-01
   1.71609268e-01 -4.27574575e-01 -2.49930024e-01 -5.08792639e-01]
 [ 2.87464947e-01 -4.34581429e-01  2.01478034e-01  2.11706057e-01
  -1.91756725e-01  2.03866273e-01 -1.17595874e-01 -1.63161933e-01]
 [ 1.38432324e-01 -3.79403472e-01 -9.70533490e-02  2.86447138e-01
  -1.20393105e-01  1.60023615e-01  1.36762187e-02 -4.09748673e-01]
 [-2.54627645e-01 -4.65800390e-02 -5.30807897e-02  1.31953333e-04
  -4.07643616e-03  5.01047015e-01 -5.37623391e-02 -1.26693606e-01]
 [-6.80139195e-03  5.88255599e-02  4.33781952e-01 -5.67014255e-02
   1.67490333e-01  1.65109202e-01 -4.16878730e-01  3.68329376e-01]
 [-3.73352855e-01 -2.48269998e-02 -2.62928128e-01  3.35028917e-01
  -4.09781963e-01  4.56565797e-01 -1.39052905e-02 -4.30786133e-01]
 [-2.15316519e-01  2.91728199e-01 -9.91543159e-02  4.74272460e-01
   7.68565759e-02  1.92980200e-01 -4.79732394e-01 -2.14067608e-01]
 [-1.38553873e-01 -3.30516398e-01 -3.49370539e-01  1.06488049e-01
  -2.41755530e-01  1.14208132e-01 -3.95094037e-01 -1.90577865e-01]
 [ 2.57438928e-01  2.42873117e-01 -2.38140360e-01  8.16483423e-02
   4.28835183e-01 -1.96137019e-02 -2.65001178e-01 -4.33588117e-01]
 [ 1.24086455e-01  1.89310119e-01 -6.71968833e-02  1.36268258e-01
  -3.73162925e-01 -4.63270962e-01 -3.25483263e-01 -5.04992425e-01]
 [-4.84717265e-02  2.88791031e-01 -4.17867512e-01 -5.04753649e-01
   6.60768002e-02  6.69142529e-02  2.80209146e-02  3.43073368e-01]
 [-3.16452622e-01  4.27599549e-01  3.48043025e-01 -4.32694107e-01
  -2.39389017e-01  2.12291226e-01 -3.75955284e-01 -2.10531149e-02]
 [ 1.44089788e-01 -7.94864446e-02 -3.37332875e-01 -3.02796841e-01
   5.14203012e-02 -1.15633361e-01 -2.51446515e-01  2.18029335e-01]
 [-2.14359343e-01 -2.87420064e-01  2.12392524e-01 -1.71383068e-01
  -3.49908829e-01 -1.73403367e-01  8.67419839e-02  2.45576322e-01]
 [-2.64333338e-01 -4.77261186e-01 -2.78458416e-01  1.68548405e-01
   3.88440415e-02  1.43483669e-01 -2.27211043e-01 -1.15172200e-01]
 [ 1.36532664e-01 -1.93898499e-01 -1.66957304e-01  2.40265757e-01
  -4.20734882e-01 -4.11551088e-01 -2.29571968e-01  1.33682147e-01]]
Bias b4:
 [-0.0362075   0.01497078  0.00164855 -0.01502291 -0.04329294  0.00695746
 -0.02734338 -0.04225151]
Weights W5:
 [[ 0.46217144]
 [-0.4714438 ]
 [-0.20130846]
 [ 0.05478074]
 [ 0.6723495 ]
 [-0.38414282]
 [ 0.74174845]
 [ 0.6656955 ]]
Bias b5:
 [-0.22101456]

In [196]:
# Test on the ANN using the last 10 days:
predictions = model.predict(X[-10:])
for i in range (10):
    if ((Y[-10+i] > 0 and predictions[i] > 0) or (Y[-10+i] <= 0 and predictions[i] <= 0)):
        print(f'Day: {10-i}:\tReal Movement: {Y[-10+i]}\tPrediction: {predictions[i]}\tMATCH')
    else:
        print(f'Day: {10-i}:\tReal Movement: {Y[-10+i]}\tPrediction: {predictions[i]}\tNO MATCH')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
Day: 10:	Real Movement: -0.04416324263826643	Prediction: [-0.01162697]	MATCH
Day: 9:	Real Movement: -0.00823834042273175	Prediction: [-0.011566]	MATCH
Day: 8:	Real Movement: 0.04603922874232036	Prediction: [-0.01161109]	NO MATCH
Day: 7:	Real Movement: -0.02810789603432695	Prediction: [-0.01206578]	MATCH
Day: 6:	Real Movement: 0.04220259077712596	Prediction: [-0.01206895]	NO MATCH
Day: 5:	Real Movement: -0.033922077118805904	Prediction: [-0.01225312]	MATCH
Day: 4:	Real Movement: -0.01705385193032183	Prediction: [-0.01128427]	MATCH
Day: 3:	Real Movement: -0.07596969728248681	Prediction: [-0.01174338]	MATCH
Day: 2:	Real Movement: 0.04939630595567479	Prediction: [-0.01166368]	NO MATCH
Day: 1:	Real Movement: -0.048868444911533415	Prediction: [-0.01164908]	MATCH

In [ ]:
## ask user if they would like to save the ANN model
choice = ''
while choice not in ['y','n']:
    choice = input('\n\nWould you like to save the ANN model? (y/n): \n')
    if choice == 'y':
        save_name = input('\n\nEnter a name for the save file: \n')
        ## if file name does not end with '.h5', add '.h5' to the file name
        if save_name[-3:] != '.h5':
            save_name += '.h5'
        model.save(save_name)
        print('\n\n')
        print('***** ANN MODEL SUCCESSFULLY SAVED AS '+save_name+' *****')
    elif choice == 'n':
        pass
    else:
        print("Invalid input: Input must be 'y' or 'n'")

Would you like to save the ANN model? (y/n):
y